In [1]:
from altitude_rl import networks
import numpy as np
import torch as t 

In [11]:
x = t.linspace(1,10,10)
print("Input: ",x[:-1])
y = x[5:]
print("Labels: ",y)
print("----------------------")
x.unfold(dimension=0, size=5, step=1)[:-1] 


Input:  tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Labels:  tensor([ 6.,  7.,  8.,  9., 10.])
----------------------


tensor([[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.],
        [3., 4., 5., 6., 7.],
        [4., 5., 6., 7., 8.],
        [5., 6., 7., 8., 9.]])

In [17]:
d=128
model = t.nn.Sequential(
     networks.MultiObsEncoder(d=d),
     t.nn.Linear(d, d),
     t.nn.ReLU(),
     t.nn.Linear(d, 4),
    #t.nn.Flatten(start_dim=0),
).to(t.float32)

In [18]:
model(data).shape

torch.Size([1, 4])

In [19]:

dataset = t.load("data/ffa_channelpark.pt", weights_only=False)

In [20]:
dataset.tensors

(tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.6064, 0.9282, 0.6250, 0.0000, 0.0000],
         ...,
         [0.0984, 0.3879, 0.3333, 0.0000, 0.0000],
         [0.0973, 0.3901, 0.3333, 0.0000, 0.0000],
         [0.0961, 0.3928, 0.3333, 0.0000, 0.0000]], dtype=torch.float16),
 tensor([0., 0., 0.,  ..., 0., 0., 0.], dtype=torch.float16))

In [21]:
vec = t.zeros((1024))
vec[-1] = 1
vec[-30:]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [22]:
obs = t.zeros((30,5))
i=0

In [23]:
t.atan2( obs[i:i+30,2],obs[i:i+30,3]).shape

torch.Size([30])

In [24]:
obs = t.tensor([
    [1.0, 1.1],  # obs1
    [2.0, 2.1],  # obs2
    [3.0, 3.1],  # obs3
    [4.0, 4.1],  # obs4
])

window_size = 4

# Use unfold on the time dimension (dim=0)
windows = obs.unfold(dimension=0, size=window_size, step=1)  # shape: [num_windows, window_size, D]

In [25]:
windows.flatten(start_dim=1,end_dim=2)

tensor([[1.0000, 2.0000, 3.0000, 4.0000, 1.1000, 2.1000, 3.1000, 4.1000]])

In [26]:
from math import *
atan2(0,1)/pi*180

0.0

In [32]:
obs = t.zeros((30,5))
angles =  10 * obs[:, 2] * t.pi / 180
cosi = t.stack([t.cos(angles), t.sin(angles)], dim=1)
x = t.cat((obs[:, :2], cosi,obs[:,3:]), dim=1)
x


tensor([[0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0

: 

: 

: 